openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing contacts
tags:
  - name: Contacts
    description: Operations related to contacts
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-ppc1.onrender.com
paths:
  /contacts:
    $ref: '../swagger/paths/contacts/index.yaml'
  /contacts/{contactId}:
    $ref: '../swagger/paths/contacts/{id}/index.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
